### PR TITLE
Mention dependency on Python

### PR DESCRIPTION
**Pull request by rushmorem**

### CODE REVIEW

**Comment by rushmorem** [comment]
[clabot:check]

**Comment by shawntabrizi** [comment]
@rushmorem sorry, where does the Python dependency come from?

**Comment by rushmorem** [comment]
When I run `yarn install` without `python` in my `PATH`, I run into the following error:-

```
error /tmp/substrate-ui/node_modules/blake2js: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /tmp/substrate-ui/node_modules/blake2js
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.15.1 | linux | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (/nix/store/y6z3iz4x9dccx4a9d5m6fva0hyjav7g5-nodejs-8.15.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/nix/store/y6z3iz4x9dccx4a9d5m6fva0hyjav7g5-nodejs-8.15.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:16)
gyp ERR! stack     at F (/nix/store/y6z3iz4x9dccx4a9d5m6fva0hyjav7g5-nodejs-8.15.1/lib/node_modules/npm/node_modules/which/which.js:68:16)
gyp ERR! stack     at E (/nix/store/y6z3iz4x9dccx4a9d5m6fva0hyjav7g5-nodejs-8.15.1/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /nix/store/y6z3iz4x9dccx4a9d5m6fva0hyjav7g5-nodejs-8.15.1/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /nix/store/y6z3iz4x9dccx4a9d5m6fva0hyjav7g5-nodejs-8.15.1/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /nix/store/y6z3iz4x9dccx4a9d5m6fva0hyjav7g5-nodejs-8.15.1/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.19.56
gyp ERR! command "/nix/store/y6z3iz4x9dccx4a9d5m6fva0hyjav7g5-nodejs-8.15.1/bin/node" "/nix/store/y6z3iz4x9dccx4a9d5m6fva0hyjav7g5-nodejs-8.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/substrate-ui/node_modules/blake2js
gyp ERR! node -v v8.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by shawntabrizi** [comment]
Ah yes, because of the pesky `node-gyp`.

Okay Ill add it :)

**Pull request merged**
